version: "3"
services:
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
          - postgres_data:/var/lib/postgresql/data
  exchange:
    build: .
    ports:
      - "8000:8000"
    container_name: django_app
    depends_on:
      - db

volumes:
  postgres_data:
