version: "3"
services:
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
          - postgres_data:/var/lib/postgresql/data
  exchange:
    build: .
    ports:
      - "8000:8000"
    container_name: django_app
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "poetry run python manage.py collectstatic --noinput &&
             poetry run python manage.py migrate &&
             poetry run python manage.py fill_db && 
             poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - exchange

volumes:
  postgres_data: