# Generated by Django 5.1.5 on 2025-02-01 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL("CREATE SCHEMA course;"),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_comment='Код валюты', max_length=3, verbose_name='Код валюты')),
                ('name', models.CharField(db_comment='Наименование валюты', max_length=128, verbose_name='Наименование валюты')),
                ('sign', models.CharField(db_comment='Символ валюты', max_length=16, verbose_name='Символ валюты')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'db_table': '"course"."currency"',
                'db_table_comment': 'Валюты',
                'indexes': [models.Index(fields=['code'], name='ix_currency$code')],
                'constraints': [models.UniqueConstraint(fields=('code',), name='iu_currency$code')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(db_comment='Курс обмена единицы базовой валюты к единице целевой валюты', decimal_places=6, max_digits=8, verbose_name='Курс обмена единицы базовой валюты к единице целевой валюты')),
                ('base_currency', models.ForeignKey(db_comment='Базовая валюта', db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='base_currencies', to='api.currency', verbose_name='Базовая валюта')),
                ('target_currency', models.ForeignKey(db_comment='Целевая валюта', db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='target_currencies', to='api.currency', verbose_name='Целевая валюта')),
            ],
            options={
                'verbose_name': 'Курс обмена',
                'verbose_name_plural': 'Курсы обмена',
                'db_table': '"course"."exchange_rate"',
                'db_table_comment': 'Курсы обмена',
                'indexes': [models.Index(fields=['base_currency', 'target_currency'], name='ix_base_cur$target_cur')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'target_currency'), name='iu_base_currency_id$target_currency_id')],
            },
        ),
    ]
