# Generated by Django 5.1.5 on 2025-02-09 11:54

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(db_comment='Курс обмена единицы базовой валюты к единице целевой валюты', decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Курс обмена единицы базовой валюты к единице целевой валюты'),
        )
    ]
